# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.30.0

      - name: Client dry-run apply (sanity check)
        run: |
          kubectl apply --dry-run=client -f src/ -R

      - name: Install kubeconform
        run: |
          set -euo pipefail
          KUBECONFORM_VERSION="v0.6.7"
          curl -sSL -o kubeconform.tar.gz \
            "https://github.com/yannh/kubeconform/releases/download/${KUBECONFORM_VERSION}/kubeconform-linux-amd64.tar.gz"
          tar -xzf kubeconform.tar.gz
          sudo mv kubeconform /usr/local/bin/
          kubeconform -version

      - name: Validate manifests with kubeconform
        run: |
          kubeconform \
            -strict \
            -summary \
            -ignore-missing-schemas \
            -recursive src/
